server:
  port: 8081

spring:
  application:
    name: demo
# Clickhouse 配置
  clickhouse:
    url: jdbc:clickhouse://clickhouse.clickhouse.orb.local:8123/default
# MySQL 配置
  datasource:
    mysql:
      enabled: false
      url: jdbc:mysql://mysql.sql.orb.local:3306/testdb
      username: root
      password:
      driver-class-name: com.mysql.cj.jdbc.Driver
# Redis 配置
  redis:
    cluster:
      enabled: false
      nodes:
        - redis-1.redis.orb.local:6379
        - redis-2.redis.orb.local:6379
        - redis-3.redis.orb.local:6379
      timeout: 2000
      max-attempts: 3
      # password: your-password # 如果沒設密碼，這行可以移除
# RocketMQ 配置
  rocketmq:
    enabled: false  # 暫時關閉
    name-server: namesrv.rocketmq.orb.local:9876
    producer:
      group: test-producer-group
      send-message-timeout: 3000
      retry-times-when-send-failed: 2
# Kafka MQ 配置
  kafka:
    bootstrap-servers: localhost:9092
    streams:
      application-id: hf-risk-custom-buckets
      properties:
        processing.guarantee: exactly_once_v2
# MQ topic
topics:
  events: risk-events
  alerts: risk-alerts
