server:
  port: 8081

# Mock 用
mock:
  kafka:
    clickhouse: false
    risk-control: false

# MQ topic(不走 spring boot 配置)
topics:
  events: risk-events
  alerts: risk-alerts

# Redis 配置(不走 spring boot 默認配置)
redis:
  enabled: true
  clusterMode: false
  timeout: 2000 # 也可以寫 2s
  max-attempts: 3
  # password: your-password # 如果沒設密碼，這行可以移除
  nodes:
    - redis-single.redis.orb.local:6379

# Clickhouse 配置
clickhouse:
  enabled: false
  url: jdbc:clickhouse://clickhouse.clickhouse.orb.local:8123/default

# RocketMQ 配置
rocketmq:
  enabled: false  # 暫時關閉
  name-server: namesrv.rocketmq.orb.local:9876
  producer:
    group: test-producer-group
    send-message-timeout: 3000
    retry-times-when-send-failed: 2

# Kafka MQ 配置
kafka:
  enabled: true
  bootstrap-servers: localhost:9092
  streams:
    application-id: hf-risk-custom-buckets
    properties:
      processing.guarantee: exactly_once_v2
  producer:
    records-per-second: 10
    duration-seconds: 5

# MySQL 配置
datasource:
  enabled: false
  mysql:
    url: jdbc:mysql://mysql.sql.orb.local:3306/testdb
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

spring:
  application:
    name: demo
